version: "3.9"

services:
  spike-message-board-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql-data:/var/lib/mysql

  spike-message-board-backend:
    build:
      context: ./experiment--express-with-nextjs
      dockerfile: Dockerfile
    environment:
      PORT: 3001
      DATABASE_URL: "mysql://appuser:app_pass@spike-message-board-mysql:3306/app"
    depends_on:
      - spike-message-board-mysql

  spike-message-board-nginx:
    image: nginx:latest
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql-data: {}
