version: "3.9"

services:
  spike-message-board-mysql:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  spike-message-board-backend:
    build:
      context: ../../experiment--express-with-nextjs
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - spike-message-board-mysql

  spike-message-board-nginx:
    image: nginx:latest
    depends_on:
      - spike-message-board-backend
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql-data: {}
